# Generated by Django 4.2.5 on 2023-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrot_app", "0003_userprofile_birthdate_userprofile_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="post_images/")),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="images",
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(to="carrot_app.image"),
        ),
    ]
