# Generated by Django 4.2.5 on 2023-10-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0005_alter_userprofile_birthdate_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannertemperature',
            name='total_score',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='mannertemperature',
            name='total_votes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
