# Generated by Django 4.2.5 on 2023-10-05 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0008_mannertemperature_last_vote_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannertemperature',
            name='last_vote_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
