# Generated by Django 4.2.5 on 2023-10-05 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0009_alter_mannertemperature_last_vote_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mannertemperature',
            name='last_vote_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
